apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-lo
  labels:
    app: mailu-lo
    component: deployment
spec:
  selector:
    matchLabels:
      app: mailu-lo
  template:
    metadata:
      labels:
        app: mailu-lo
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: mailu-lo
        env:
        - name: BACKEND
          value: http://n100.x.jsx.jp:4080
---
apiVersion: v1
kind: Service
metadata:
  name: mailu-lo
  labels:
    app: mailu-lo
    component: service
spec:
  selector:
    app: mailu-lo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mailu-lo
  labels:
    app: mailu-lo
    component: route
spec:
  parentRefs:
  - name: web-gateway
    namespace: gateway-system
  hostnames:
  - "mailu.jsx.jp"
  - "mailu.x.jsx.jp"
  rules:
  - backendRefs:
    - name: mailu-lo
      port: 80
