apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-lo
  labels:
    app: next-lo
    component: deployment
spec:
  selector:
    matchLabels:
      app: next-lo
  template:
    metadata:
      labels:
        app: next-lo
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: next-lo
        env:
        - name: BACKEND
          value: http://next.proxy.jsx.jp:3458
---
apiVersion: v1
kind: Service
metadata:
  name: next-lo
  labels:
    app: next-lo
    component: service
spec:
  selector:
    app: next-lo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: next-lo
  labels:
    app: next-lo
    component: route
spec:
  parentRefs:
  - name: web-gateway
    namespace: gateway-system
  hostnames:
  - "next-lo.jsx.jp"
  - "next-lo.x.jsx.jp"
  rules:
  - backendRefs:
    - name: next-lo
      port: 80
---
apiVersion: gateway.nginx.org/v1alpha1
kind: AuthenticationFilter
metadata:
  name: next-lo
  labels:
    app: next-lo
    component: auth
spec:
  type: Basic
  basic:
    secret:
      name: basic-auth
