apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop-lo
  labels:
    app: webtop-lo
    component: deployment
spec:
  selector:
    matchLabels:
      app: webtop-lo
  template:
    metadata:
      labels:
        app: webtop-lo
        component: workload
    spec:
      containers:
      - image: ghcr.io/jobscale/reverse-proxy
        name: webtop-lo
        env:
        - name: BACKEND
          value: http://dark.jsx.jp:2999
---
apiVersion: v1
kind: Service
metadata:
  name: webtop-lo
  labels:
    app: webtop-lo
    component: service
spec:
  selector:
    app: webtop-lo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtop-lo
  labels:
    app: webtop-lo
    component: ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - secret'
spec:
  ingressClassName: nginx
  tls:
  - secretName: jsxjp-tls
    hosts: [ "kde.jsx.jp", "kde.x.jsx.jp" ]
  rules:
  - host: kde.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: webtop-lo
            port:
              number: 80
  - host: kde.x.jsx.jp
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: webtop-lo
            port:
              number: 80
