---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-nodejs
  namespace: net-apps
spec:
  selector:
    matchLabels:
      app: proxy-nodejs
  template:
    metadata:
      labels:
        app: proxy-nodejs
        component: workload
    spec:
      containers:
      - name: proxy-nodejs
        image: ghcr.io/jobscale/proxy-nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-nodejs
  namespace: net-apps
spec:
  selector:
    app: proxy-nodejs
  type: LoadBalancer
  ports:
  - name: tcp
    nodePort: 30312
    port: 3128
    targetPort: 3128
    protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: proxy-nodejs
  namespace: net-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proxy-nodejs
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
